//
//  PassFlowStateCode.swift
//  MobilePassSDK
//
//  Created by Erinc Cakir on 1.06.2023.
//

import Foundation

enum PassFlowStateCode: Int, Codable {
    case SCAN_QRCODE_NEED_PERMISSION = 1001;
    case SCAN_QRCODE_PERMISSION_GRANTED = 1002;
    case SCAN_QRCODE_PERMISSION_REJECTED = 1003;
    case SCAN_QRCODE_STARTED = 1004;
    case SCAN_QRCODE_INVALID_CONTENT = 1005;
    case SCAN_QRCODE_INVALID_FORMAT = 1006;
    case SCAN_QRCODE_NO_MATCH = 1007;
    case SCAN_QRCODE_FOUND = 1008;
    case SCAN_QRCODE_ERROR = 1009;
    case CANCELLED_BY_USER = 2001;
    case CANCELLED_WITH_INVALID_QRCODE = 2002;
    case CANCELLED_WITH_ERROR = 2003;
    case CANCELLED_WITH_MOCK_LOCATION = 2004;
    case CANCELLED_TO_GO_SETTINGS = 2005;
    case INVALID_QRCODE_TRIGGER_TYPE = 3101;
    case INVALID_QRCODE_MISSING_CONTENT = 3102;
    case INVALID_ACTION_LIST_EMPTY = 3201;
    case INVALID_ACTION_TYPE = 3202;
    case INVALID_BLUETOOTH_QRCODE_DATA = 3301;
    case INVALID_BLUETOOTH_DIRECTION = 3302;
    case INVALID_BLUETOOTH_HARDWARE_ID = 3303;
    case INVALID_BLUETOOTH_RELAY_NUMBER = 3304;
    case INVALID_REMOTE_ACCESS_QRCODE_DATA = 3401;
    case INVALID_REMOTE_ACCESS_QRCODE_ID = 3402;
    case PROCESS_ACTION_STARTED = 4101;
    case PROCESS_ACTION_BLUETOOTH = 4102;
    case PROCESS_ACTION_LOCATION = 4103;
    case PROCESS_ACTION_REMOTE_ACCESS = 4104;
    case PROCESS_ACTION_LOCATION_NEED_PERMISSION = 4105;
    case PROCESS_ACTION_LOCATION_NEED_ENABLED = 4106;
    case PROCESS_ACTION_LOCATION_PERMISSION_GRANTED = 4107;
    case PROCESS_ACTION_LOCATION_PERMISSION_REJECTED = 4108;
    case PROCESS_ACTION_BLUETOOTH_NEED_PERMISSION = 4109;
    case PROCESS_ACTION_BLUETOOTH_NEED_ENABLED = 4110;
    case PROCESS_ACTION_BLUETOOTH_PERMISSION_GRANTED = 4111;
    case PROCESS_ACTION_BLUETOOTH_PERMISSION_REJECTED = 4112;
    case RUN_ACTION_BLUETOOTH_STARTED = 4201;
    case RUN_ACTION_BLUETOOTH_OFF_WAITING = 4202;
    case RUN_ACTION_BLUETOOTH_OFF_NO_WAIT = 4203;
    case RUN_ACTION_BLUETOOTH_START_SCAN = 4204;
    case RUN_ACTION_BLUETOOTH_TIMEOUT = 4205;
    case RUN_ACTION_BLUETOOTH_CONNECTING = 4206;
    case RUN_ACTION_BLUETOOTH_CONNECTED = 4207;
    case RUN_ACTION_BLUETOOTH_CONNECTION_FAILED = 4208;
    case RUN_ACTION_BLUETOOTH_PASS_SUCCEED = 4209;
    case RUN_ACTION_BLUETOOTH_PASS_FAILED = 4210;
    case RUN_ACTION_LOCATION_WAITING = 4301;
    case RUN_ACTION_LOCATION_VALIDATED = 4302;
    case RUN_ACTION_LOCATION_FAILED = 4303;
    case RUN_ACTION_REMOTE_ACCESS_STARTED = 4401;
    case RUN_ACTION_REMOTE_ACCESS_REQUEST = 4402;
    case RUN_ACTION_REMOTE_ACCESS_UNAUTHORIZED = 4403;
    case RUN_ACTION_REMOTE_ACCESS_DEVICE_NOT_CONNECTED = 4404;
    case RUN_ACTION_REMOTE_ACCESS_DEVICE_TIMEOUT = 4405;
    case RUN_ACTION_REMOTE_ACCESS_NO_NETWORK = 4406;
    case RUN_ACTION_REMOTE_ACCESS_REQUEST_FAILED = 4407;
    case RUN_ACTION_REMOTE_ACCESS_REQUEST_SUCCEED = 4408;
    case RUN_ACTION_REMOTE_ACCESS_PASS_SUCCEED = 4409;
    case RUN_ACTION_REMOTE_ACCESS_PASS_FAILED = 4410;
}
